// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package data

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CheckIn struct {
	ID        int32            `json:"id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	EventID   int32            `json:"event_id"`
	MemberID  int32            `json:"member_id"`
	PnmID     int32            `json:"pnm_id"`
}

type Event struct {
	ID          int32            `json:"id"`
	OrgID       int32            `json:"org_id"`
	Title       string           `json:"title"`
	Description pgtype.Text      `json:"description"`
	Start       pgtype.Timestamp `json:"start"`
	Venue       pgtype.Text      `json:"venue"`
	Location    pgtype.Text      `json:"location"`
	End         pgtype.Timestamp `json:"end"`
	Category    pgtype.Text      `json:"category"`
}

type Organization struct {
	ID           int32       `json:"id"`
	Name         string      `json:"name"`
	Code         string      `json:"code"`
	ContactName  pgtype.Text `json:"contact_name"`
	ContactEmail pgtype.Text `json:"contact_email"`
	Url          pgtype.Text `json:"url"`
	IfcUrl       pgtype.Text `json:"ifc_url"`
	Address      pgtype.Text `json:"address"`
}

type Reservation struct {
	ID      int32 `json:"id"`
	UserID  int32 `json:"user_id"`
	EventID int32 `json:"event_id"`
}

type Session struct {
	Token  string             `json:"token"`
	Data   []byte             `json:"data"`
	Expiry pgtype.Timestamptz `json:"expiry"`
}

type User struct {
	ID         int32            `json:"id"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
	Kerb       string           `json:"kerb"`
	Email      pgtype.Text      `json:"email"`
	Phone      pgtype.Text      `json:"phone"`
	Department pgtype.Text      `json:"department"`
	ClassYear  pgtype.Text      `json:"class_year"`
	Gender     pgtype.Text      `json:"gender"`
	Residence  pgtype.Text      `json:"residence"`
	Legacy     pgtype.Text      `json:"legacy"`
	OrgID      pgtype.Int4      `json:"org_id"`
	IsAdmin    bool             `json:"is_admin"`
	BidStatus  pgtype.Text      `json:"bid_status"`
	Race       pgtype.Text      `json:"race"`
	FirstGen   pgtype.Bool      `json:"first_gen"`
	Name       pgtype.Text      `json:"name"`
}
