// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package data

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CheckIn struct {
	ID        int32
	CreatedAt pgtype.Timestamptz
	EventID   int32
	MemberID  int32
	PnmID     int32
}

type Event struct {
	ID          int32
	OrgID       int32
	Title       string
	Description pgtype.Text
	Start       pgtype.Timestamptz
	Venue       pgtype.Text
	Location    pgtype.Text
	End         pgtype.Timestamptz
}

type Organization struct {
	ID           int32
	Name         string
	Code         string
	ContactName  pgtype.Text
	ContactEmail pgtype.Text
	Url          pgtype.Text
	IfcUrl       pgtype.Text
	Address      pgtype.Text
}

type Reservation struct {
	ID      int32
	UserID  int32
	EventID int32
}

type Session struct {
	ID        int32
	Token     pgtype.UUID
	UserID    int32
	CreatedOn pgtype.Timestamptz
	ExpiresOn pgtype.Timestamptz
}

type User struct {
	ID         int32
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	Kerb       string
	Email      pgtype.Text
	Phone      pgtype.Text
	Department pgtype.Text
	ClassYear  pgtype.Text
	Gender     pgtype.Text
	Residence  pgtype.Text
	Legacy     pgtype.Text
	OrgID      pgtype.Int4
	IsAdmin    bool
	BidStatus  pgtype.Text
}
